### PR TITLE
(FULFILL-1574) Rework PPA install to no longer force version pinning

### PR DESCRIPTION
**Pull request by eggilbert**
@jolexa @danrue @farrellit 

As it turns out, the Ubuntu PPA is mean and removes old versions as new ones are released (is that normal/standard behavior?). When a playbook pins to a version in the PPA, this causes the playbook to break when new versions are released, such as last week, and also https://github.com/SPSCommerce/ansible-role-nginx/pull/6.

Now the role supports a new `nginx_ppa_version_string` variable instead of `nginx_version` so you can pin to a version if you dare, but are no longer required to. The default value is now `nginx` which will install the latest out of the PPA, whatever that happens to be.

I've made the old `install_ppa` variable continue to work backwards-compatibly with my renamings, but not `nginx_version` as it's previous default is broken and is the reason for this PR. This should allow playbooks to blindly update to this and continue to get _a version from the PPA_ and a working installation, instead of pinning to a version no longer in existence (unless the playbook is updated to use the new `nginx_ppa_version_string` variable).

This should probably be at least a minor version bump.

**Bonus Changes**
- The `files` attribute of `nginx_sites` has always bothered me that it's required, so now it's optional. It was actually really hard to make it optional due to the `with_subelements` directive, which seemed to be evaluated before `when` conditions. It looks like there's a nice way to do in ansible 2.0 though.

**Example usages**
Updated to use the new hotness
```
- role: nginx
  nginx_ppa_install: true
  nginx_sites:
    - name: "{{ app_name }}.conf"
      template: templates/nginx.conf.j2
```

Still works backwards-compatibly
```
- role: nginx
  install_ppa: true
  nginx_sites:
    - name: "{{ app_name }}.conf"
      template: templates/nginx.conf.j2
      files: []
```

Risky version pinning
```
- role: nginx
  nginx_ppa_install: true
  nginx_ppa_version_string: nginx=1.10.0-0+trusty0
  nginx_sites:
    - name: "{{ app_name }}.conf"
      template: templates/nginx.conf.j2
```

No PPA
```
- role: nginx
  nginx_sites:
    - name: "{{ app_name }}.conf"
      template: templates/nginx.conf.j2
```

### CODE REVIEW

**Comment by danrue** [comment]
Looks great to me. My only suggestion is to take your very excellent example usage posted to this PR and drop it into the README, too. 👍

**Comment by eggilbert** [comment]
This role gets used quite a bit, so I think we're due for 1.0.0?

**Comment by danrue** [comment]
I think trying to tie nginx to a particular version without implementing our own package repos is difficult, and riskier (as we've seen) than not pinning it. I agree with the trade-offs made here. Since it is a rather large change, at least in terms of this role, bumping the major would be prudent.

**Comment by eggilbert** [comment]
I'm going to test this out a little more first before merging.

**Comment by eggilbert** [comment]
Okay, I had 3 successful stack deployments using these changes, and am convinced things are good now. I had one instance fail it's health check earlier and I'm not sure why, but nothing seems to indicate it was related to this.

**Pull request merged**
