### PR TITLE
External templates

### PR DESCRIPTION
**Pull request by farrellit**
* Support external templates in the sites list 
  - allows the role to handle arbitrary config and still handle available/enabled site links 
* added testing config for such a site which is tested with a `rake` 
* added a readme

### CODE REVIEW

**Comment by danrue** [comment]
looks like good changes to me :+1:

**Comment by eggilbert** [comment]
Testing it out right now for fulfillment-data-entry-bridge

**Comment by eggilbert** [comment]
This works for me :+1: 

```
- role: nginx
  nginx_sites:
    - name: "{{ app_name }}.conf"
      template: templates/nginx.conf.j2
      files: []
```

**Comment by farrellit** [comment]
It doesn't look possible yet to skip missing, but that will be possible in Ansible 2.0.  https://docs.ansible.com/playbooks_loops.html#looping-over-subelements mentions it but of course for some reason Ansible Doc is _ahead_ of release.

**Comment by farrellit** [comment]
0.11.0 built and in S3

**Pull request merged**
